name: Publish to VS Code Marketplace

on:
  workflow_dispatch:

jobs:
  publish:
    uses: CodingWithCalvin/.github/.github/workflows/vsc-vsix-publish.yml@main
    with:
      extension-name: VSC-MCPServer
      display-name: "VSC as MCP"
      marketplace-id: CodingWithCalvin.VSC-MCPServer
      description: "Supercharge your AI coding assistants with VS Code's powerful language intelligence!"
      hashtags: "#mcp #ai #claude"
    secrets: inherit
